### ISSUE TITLE
Getting this error?

### ISSUE THREAD

**Issue by yomasa** [ArduinoHannover/ESPMailer#1]
Arduino: 1.6.7 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

In file included from /Users/jblanco-us/Documents/Arduino/libraries/ESPMailer-master/examples/TestMail/TestMail.ino:2:0:
/Users/jblanco-us/Documents/Arduino/libraries/ESPMailer-master/ESPMailer.h:3:17: fatal error: NTP.h: No such file or directory
 #include <NTP.h>
                 ^
compilation terminated.
exit status 1
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by soundstorm** [comment]
Have you installed the Library https://github.com/ArduinoHannover/NTP ?

**Comment by yomasa** [comment]
ok got it compiling,  
once it connects to wifi I get this...
Error while processing following command:


any idea?

**Comment by soundstorm** [comment]
Then you might have missed the Time.h - if you got it in your Libraries already, then include it in your main sketch (but Arduino should do this automatically with 1.6.6+).
I'll add the dependency description to the Readme.

**Comment by yomasa** [comment]
ok got that working, I am getting this now after it logs in to ssid and starts sending email

Exception (9):
epc1=0x401057f5 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000007 depc=0x00000000

ctx: cont 
sp: 3ffefcd0 end: 3ffeffd0 offset: 01a0

> > > stack>>>
> > > 3ffefe70:  3fff09c0 00000000 3ffe86d3 40106fc0  
> > > 3ffefe80:  3fff09a8 40106fd7 3ffe86d3 40106fc0  
> > > 3ffefe90:  3ffeff54 00000001 00000020 40205872  
> > > 3ffefea0:  00000010 00000001 3ffeff00 4020584e  
> > > 3ffefeb0:  00000010 00000001 3ffeff54 402058a6  
> > > 3ffefec0:  3fff0948 3ffe8465 3ffeff54 40205c71  
> > > 3ffefed0:  3fffdad0 3ffe83ef 3ffeff00 3ffeefa8  
> > > 3ffefee0:  3fffdad0 3ffe83ef 3ffeff20 40205ca6  
> > > 3ffefef0:  3fffdad0 3ffe83ef 3ffeff20 40203563  
> > > 3ffeff00:  3fff09c8 0000001f 00000010 40204f60  
> > > 3ffeff10:  3fffdad0 3ffe83ef 3ffeeee8 402021ef  
> > > 3ffeff20:  3ffe8534 3ffe86d2 3ffe8498 00000000  
> > > 3ffeff30:  000003e8 feefeffe 00000000 00000000  
> > > 3ffeff40:  3fff0908 3fff0928 3fff0948 3fff0960  
> > > 3ffeff50:  3fff0978 3fff00b0 0000000f 00000000  
> > > 3ffeff60:  3fff0620 0000000f 00000000 3fff08c0  
> > > 3ffeff70:  0000000f 00000000 3fff08d8 0000000f  
> > > 3ffeff80:  00000000 3fff08f0 0000000f 00000000  
> > > 3ffeff90:  00000019 3f800000 3fff0998 0000000f  
> > > 3ffeffa0:  0000000f feefeffe feefeffe feefeffe  
> > > 3ffeffb0:  feefeffe 00000000 3ffeefa1 4020480c  
> > > 3ffeffc0:  feefeffe feefeffe 3ffeefb0 40100114  
> > > <<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x42
csum 0x42
~ld

**Comment by soundstorm** [comment]
Ok, I'll check that. May be a memory fault. If I do the rewrite of the Library to match PHPMailer, it should be gone. I'll comment as soon as the new push is online.
