### ISSUE TITLE
Not encode 

### ISSUE THREAD

**Issue by yomasa** [ArduinoHannover/ESPMailer#3]
I have an email server that the username and password are not encoded, How do I do that? Looks like ESPMailer encodes all the time?

**Comment by soundstorm** [comment]
Surely not encoded so completely plain? If AUTH PLAIN does not do the job, I'll have a look. Both, AUTH PLAIN and AUTH LOGIN are unencrypted, but base64 encoded. I've never seen unencoded login, but if you have a working example of the communication paste it here.

**Comment by yomasa** [comment]
I'm trying to login without base64 encoded, where do I set that option?
