### ISSUE TITLE
TestMail compiling error

### ISSUE THREAD

**Issue by Christian20** [ArduinoHannover/ESPMailer#6]
Hello,

I tried to run the example you provided with the library, but I get the following error:

Arduino: 1.8.2 (Windows 10), Board: "WeMos D1 R2 & mini, 80 MHz, 921600, 4M (3M SPIFFS)"

C:\Users\Chris\Documents\Arduino\libraries\ESPMailer-master\ESPMailer.cpp: In member function 'boolean ESPMailer::send()':

C:\Users\Chris\Documents\Arduino\libraries\ESPMailer-master\ESPMailer.cpp:285:25: error: 'weekday' was not declared in this scope

   dayShortStr(weekday(tm))

                         ^

C:\Users\Chris\Documents\Arduino\libraries\ESPMailer-master\ESPMailer.cpp:285:26: error: 'dayShortStr' was not declared in this scope

   dayShortStr(weekday(tm))

                          ^

C:\Users\Chris\Documents\Arduino\libraries\ESPMailer-master\ESPMailer.cpp:288:9: error: 'day' was not declared in this scope

   day(tm),

         ^

C:\Users\Chris\Documents\Arduino\libraries\ESPMailer-master\ESPMailer.cpp:289:25: error: 'month' was not declared in this scope

   monthShortStr(month(tm)),

                         ^

C:\Users\Chris\Documents\Arduino\libraries\ESPMailer-master\ESPMailer.cpp:289:26: error: 'monthShortStr' was not declared in this scope

   monthShortStr(month(tm)),

                          ^

C:\Users\Chris\Documents\Arduino\libraries\ESPMailer-master\ESPMailer.cpp:290:10: error: 'year' was not declared in this scope

   year(tm),

          ^

C:\Users\Chris\Documents\Arduino\libraries\ESPMailer-master\ESPMailer.cpp:291:10: error: 'hour' was not declared in this scope

   hour(tm),

          ^

C:\Users\Chris\Documents\Arduino\libraries\ESPMailer-master\ESPMailer.cpp:292:12: error: 'minute' was not declared in this scope

   minute(tm),

            ^

C:\Users\Chris\Documents\Arduino\libraries\ESPMailer-master\ESPMailer.cpp:293:12: error: 'second' was not declared in this scope

   second(tm),

            ^

exit status 1
Error compiling for board WeMos D1 R2 & mini.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

Could you please tell me what am I doing wrong? I have to mention that I installed both Time.h and NTP.h

Thank you!

**Comment by programmer131** [comment]
Same error

**Comment by soundstorm** [comment]
Same as ArduinoHannover/NTP#1, closing.
